# Generated by Django 4.2.2 on 2023-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetquizzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
