# Generated by Django 4.2.2 on 2023-06-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leetquizzer', '0002_remove_problem_difficulty_remove_problem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leetquizzer.difficulty'),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leetquizzer.topic'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='edge_case',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(),
        ),
    ]
