# Generated by Django 4.2.2 on 2023-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetquizzer', '0003_problem_difficulty_problem_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='option1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='option2',
            field=models.TextField(null=True),
        ),
    ]
