# Generated by Django 4.2.2 on 2023-06-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetquizzer', '0005_alter_problem_edge_case_alter_problem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
